project_id = "ecqvukaxrjtanyhknrhe"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.whatsapp-sync]
verify_jwt = true

[functions.whatsapp-react]
verify_jwt = true