// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecqvukaxrjtanyhknrhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcXZ1a2F4cmp0YW55aGtucmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTYzOTIsImV4cCI6MjA2OTAzMjM5Mn0.BTUl2z8j2QFCSVgmhWhGnWrVmcbXy_quRgi7cY5LD_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});